### ISSUE TITLE
Dependency on EntityFramework

### ISSUE THREAD

**Issue by mcintyre321** [StefH/QueryInterceptor.Core#2]
The project has a dependency on EF - is this necessary?

**Comment by StefH** [comment]
Good point !

I've split the code into 2 projects, please review it, and if all is fine, I'll upload new NuGets.

Please review...

**Comment by StefH** [comment]
Split into 2 packages, see nuget:

https://www.nuget.org/packages/QueryInterceptor.Core
&
https://www.nuget.org/packages/QueryInterceptor.EntityFramework
