### ISSUE TITLE
Support async IQueryable

### ISSUE THREAD

**Issue by RicoSuter** [StefH/QueryInterceptor.Core#3]
Please add support for async IQueryiable (required in EF when using async: `await ctx.People.SingleOrDefaultAsync()`

Steps to implement (it works for me, but only in .NET Core): 

1. Implement `IAsyncEnumerable`: 

    internal class QueryTranslator<T> : IOrderedQueryable<T>, IAsyncEnumerable<T>

Implementation:

```
        /// <summary>
        /// Returns an enumerator that iterates through a collection.
        /// </summary>
        /// <returns>
        /// An <see cref="T:System.Collections.IEnumerator" /> object that can be used to iterate through the collection.
        /// </returns>
        IAsyncEnumerator<T> IAsyncEnumerable<T>.GetEnumerator()
        {
            return _provider.ExecuteAsyncEnumerable<T>(_expression).GetEnumerator();
        }
```

2. Add async to QueryTranslatorProviderAsync: 

```
        internal IAsyncEnumerable<T> ExecuteAsyncEnumerable<T>(Expression expression)
        {
            Check.NotNull(expression, nameof(expression));

            var translated = VisitAllAndOptimize(expression);

            return ((IAsyncQueryProvider)Source.Provider).ExecuteAsync<T>(translated);
        }
```

(You can also use `dynamic` instead of `IAsyncQueryProvider`)

I cannot create a PR because I do not have the `project.json` tooling anymore and I could not find out how to implement this for .NET 4.5x etc...

The `IAsyncEnumerable` can be found in the ``System.Interactive.Async` nuget package

**Comment by StefH** [comment]
I did update the `QueryTranslator` class + some other changes. However I'm not 100% this is correct, please review the changes.

**Comment by RicoSuter** [comment]
Do you have a CI NuGet feed to test with the latest changes?

**Comment by StefH** [comment]
https://www.myget.org/F/queryinterceptor-core/api/v3/index.json

**Comment by RicoSuter** [comment]
I found another problem:  SingleOrDefaultAsync does not work...

To fix this, change

```
    internal class QueryTranslatorProviderAsync : QueryTranslatorProvider
#if EF
        , System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
#else
        , IQueryProvider
#endif
```

To

```
    internal class QueryTranslatorProviderAsync : QueryTranslatorProvider
#if EF
        , System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
#else
        , IAsyncQueryProvider
#endif
    {
```

and add

```
        IAsyncEnumerable<TResult> IAsyncQueryProvider.ExecuteAsync<TResult>(Expression expression)
        {
            Check.NotNull(expression, nameof(expression));

            return ExecuteAsyncEnumerable<TResult>(expression);
        }
```

In 

https://github.com/StefH/QueryInterceptor.Core/blob/master/src/QueryInterceptor.Core/QueryTranslatorProviderAsync.cs

**Comment by StefH** [comment]
Which NuGet did you use?
`QueryInterceptor.EntityFramework` ?
or
`QueryInterceptor.Core` ?

Because you need the `QueryInterceptor.EntityFramework`.

**Comment by RicoSuter** [comment]
With `QueryInterceptor.EntityFramework` I get the same error: 

    Message: System.InvalidOperationException : The source IQueryable doesn't implement 
    IAsyncEnumerable<System.Collections.Generic.KeyValuePair`2[System.Int32,System.Tuple`2
    [System.Int32,System.String]]>. Only sources that implement IAsyncEnumerable can be used for Entity 
    Framework asynchronous operations.

**Comment by StefH** [comment]
It seems to work fin in my example.

Get latest code for this project and run `QueryInterceptor.Core.ConsoleApp.net452` example.

**Comment by RicoSuter** [comment]
I tried with the public nuget package... Will try the ci package next wednesday... (I dont have access to the proj until then). Thank you.

**Comment by StefH** [comment]
Hello @RSuter Any update?

**Comment by RicoSuter** [comment]
Sorry, didnt look into this yet.

**Comment by RicoSuter** [comment]
Nope, still broken...

If I reference

    <PackageReference Include="Linq.PropertyTranslator.Core" Version="1.0.4" />
    <PackageReference Include="QueryInterceptor.Core" Version="1.0.6" />

in my .NET Core with EF Core app, then I get lots of

![image](https://user-images.githubusercontent.com/2603405/32302103-4670b2be-bf61-11e7-9943-1d43783af7d5.png)

**Comment by RicoSuter** [comment]
With my custom version, everything works fine: 

[QueryInterceptor.Core.zip](https://github.com/StefH/QueryInterceptor.Core/files/1435983/QueryInterceptor.Core.zip)

**Comment by RicoSuter** [comment]
I'll try QueryInterceptor.EntityFramework...

**Comment by RicoSuter** [comment]
And BTW: Its a very bad idea to have QueryInterceptor.EntityFramework reference the EF full for .NET full and EF Core for .NET Standard. What if I want to use QueryInterceptor.EntityFramework with .NET Core and full .NET?

**Comment by RicoSuter** [comment]
You should create a second package QueryInterceptor.EntityFrameworkCore

**Comment by RicoSuter** [comment]
With QueryInterceptor.EntityFramework i get lots of cast exceptions: 

![image](https://user-images.githubusercontent.com/2603405/32302466-2e123632-bf63-11e7-9ac7-73b5e3dd1fe9.png)

![image](https://user-images.githubusercontent.com/2603405/32302474-353dea14-bf63-11e7-9c78-5827b69c575d.png)

![image](https://user-images.githubusercontent.com/2603405/32302480-3c77b918-bf63-11e7-9601-5cf41084a3c6.png)

**Comment by StefH** [comment]
As a first step, I will indeed create a second package `QueryInterceptor.EntityFrameworkCore` which only references **EntityFrameworkCore**.

**Comment by RicoSuter** [comment]
This would be great, a QueryInterceptor.EntityFrameworkCore which also solves my problem :-)...
I also plan to release an open-source nuget based on your package, but until this is fixed, i cannot do that...

**Comment by StefH** [comment]
Actually there are some issues:
- EF 6.1.3 can only be used for net 45x, not compatible with netstandard 1.x or 2.x
- EF Core 1.1 only works with netstandard 1.x
- EF Core 2.0 only works with netstandard 2.x

**Comment by RicoSuter** [comment]
Yes, but EF Core also works with .NET 451+, I think you should not mix two technologies (EF and EFCore) in one package...

**Comment by StefH** [comment]
> Error	NU1202	Package Microsoft.EntityFrameworkCore 2.0.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package Microsoft.EntityFrameworkCore 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by RicoSuter** [comment]
Ok it is compatible with .NET 4.6.1 then... (via .NET Standard 2.0)
But EF Core 1.x is compatible with .NET 451: 

https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/1.1.3

**Comment by StefH** [comment]
NuGets updated : https://www.nuget.org/packages/QueryInterceptor.EntityFrameworkCore and https://www.nuget.org/packages/QueryInterceptor.EntityFramework

Please review

**Comment by RicoSuter** [comment]
Ok, i'll retry

**Comment by RicoSuter** [comment]
Thank you. After upgrading to the latest EFCore version, my application compiles, but I still get all the cast exceptions...

**Comment by RicoSuter** [comment]
You can test it yourself (here IsActive is a compiled expression): 

This works:

            var activeAcounts = this.DataContext.AccountResponsibilities
                .Where(a => a.IsActive)
                .WithCompiledExpressions()
                .ToList();

This doesn't: 

            var activeAcounts = await this.DataContext.AccountResponsibilities
                .Where(a => a.IsActive)
                .WithCompiledExpressions()
                .ToListAsync();

You can find the fix in my OP or the ZIP archive...

**Comment by StefH** [comment]
> You can find the fix in my OP or the ZIP archive... 

What do you mean?

**Comment by StefH** [comment]
Ok I see.

It fails only on netcore?

Can you create a new zip based on my current code with only the changes?

**Comment by RicoSuter** [comment]
The strange thing is that i dont use a modified ef or efcore version but your core version!?

**Comment by StefH** [comment]
I found the issue on net45x (not yet tested on core) and I know where it fails, but I don't know yet the solution...

**Comment by StefH** [comment]
I think it works now for both EF and EFCORE. Can you please check?

**Comment by RicoSuter** [comment]
Yes, it looks good... Thank you very much. I now use these dependencies: 

    <PackageReference Include="Linq.PropertyTranslator.Core" Version="1.0.4" />
    <PackageReference Include="QueryInterceptor.EntityFrameworkCore" Version="1.0.1" />

**Comment by StefH** [comment]
OK Cool. I close this issue now, if you find another problem, just open a new issue.

**Comment by RicoSuter** [comment]
Thank you for your work! The library works like a charm...

Just a side-question: Currently I have to add `.InterceptWith(new PropertyVisitor())` everywhere:

            var activeAcounts = this.DataContext.AccountResponsibilities
                .Where(a => a.IsActive)
                .InterceptWith(new PropertyVisitor())
                .ToList();

Is there a way to register it globally?

**Comment by StefH** [comment]
You can just create a (static) factory which creates the same instance from this PropertyVisitor.

**Comment by RicoSuter** [comment]
I currently use an extension method: 

        public static IQueryable<T> WithCompiledExpressions<T>(this IQueryable<T> source)
        {
            return source.InterceptWith(new PropertyVisitor());
        }

do you mean that?
Can you provide a simple sample so I understand what you mean by static factory? The main problem here is that InterceptWith must be called right before ToListAsync/SingleAsync/etc... and i call it on the DataContext's proprerties transparently..

See https://github.com/StefH/QueryInterceptor.Core/issues/4

**Comment by StefH** [comment]
See https://github.com/StefH/QueryInterceptor.Core/blob/master/test/QueryInterceptor.Core.ConsoleApp.net452/EqualsToNotEqualsVisitorFactory.cs
